minX: 48
minZ: 32
maxX: 80
maxZ: 64
worldName: world
collectAnimals: true
collectItems: true
annonceInventoryItemsOnPlayerJoin: true
annonceInventoryAnimalsOnPlayerJoin: true
annonceNewItems: true
annonceNewAnimals: true
updateItemsOnChestClosed: true
updateAnimalsOnAnimalFeed: true
messagePrefix: "\xa7o\xa77[\xa7aItemCollector\xa77]\xa7r"
annonceInventoryItemsOnPlayerJoinMessage: "\xa74Item collection: \xa72<nbCollectedItems>\
  \ / <nbTotalItems>"
annonceInventoryAnimalsOnPlayerJoinMessage: "\xa74Animal collection: \xa72 <nbCollectedAnimals>\
  \ / <nbTotalAnimals>"
annonceNewItemsMessage: "\xa74New item in the collection: \xa7l\xa7a<itemName>"
annonceNewAnimalsMessage: "\xa74New animal in the collection: \xa7l\xa7a<animalName>"
itemsCollection:
- '1': true
  '1:1': true
  '1:2': true
  '1:3': true
  '1:4': true
  '1:5': true
  '1:6': true
  '2': true
  '3': true
  '3:1': true
  '3:2': true
  '4': true
  '5:1': true
  '5:2': true
animalsCollection:
- rabbit: true
  skeleton_horse: true
  cow: true
  pig: true
