# boundaries of the region where the items/Creatures must be brought back
minX: 48
minZ: 32
maxX: 80
maxZ: 64

# name of the world containing the region where the items/Creatures must be brought back
worldName: world

# On/Off features
collectCreatures: true
collectItems: true
annonceInventoryItemsOnPlayerJoin: true
annonceInventoryCreaturesOnPlayerJoin: true
annonceNewItems: true
annonceNewCreatures: true
updateItemsOnChestClosed: true
updateCreaturesOnCreatureFeed: true

# Messages
messagePrefix: "\xa7o\xa77[\xa7aItemCollector\xa77]\xa7r"
annonceInventoryItemsOnPlayerJoinMessage: "\xa74Item collection: \xa72<nbCollectedItems>\
  \ / <nbTotalItems>"
annonceInventoryCreaturesOnPlayerJoinMessage: "\xa74Creature collection: \xa72 <nbCollectedCreatures>\
  \ / <nbTotalCreatures>"
annonceNewItemsMessage: "\xa74New item in the collection: \xa7l\xa7a<itemName>"
annonceNewCreaturesMessage: "\xa74New Creature in the collection: \xa7l\xa7a<CreatureName>"

# List of items Ids that players will try to collect
# www.minecraftinfo.com/idlist.htm
itemsCollection:
- '1': true
  '1:1': true
  '1:2': true
  '1:3': true
  '1:4': true
  '1:5': true
  '1:6': true
  '2': true
  '3': true
  '3:1': true
  '3:2': true
  '4': true
  '5:1': true
  '5:2': true
  '5:3': true
  '5:4': true
  '5:5': true
  '6': true
  '6:1': true
  '6:2': true
  '6:3': true
  '6:4': true
  '6:5': true
  '7': false
  '8': false
  '9': false
  '10': false
  '11': false
  '12': true
  '12:1': true
  '13': true
  '14': true
  '15': true
  '16': true
  '17': true
  '17:1': true
  '17:2': true
  '17:3': true
  '17:4': true
  '17:5': true
  '18': true
  '18:1': true
  '18:2': true
  '18:3': true
  '19': true
  '19:1': true
  '20': true
  '21': true
  '22': true
  '23': true
  '24': true
  '24:1': true
  '24:2': true
  '25': true
  '26': false
  '27': true
  '28': true
  '29': true
  '30': true
  '31': true
  '31:1': true
  '31:2': true
  '32': true
  '33': true
  '34': false
  '35': true
  '35:1': true
  '35:2': true
  '35:3': true
  '35:4': true
  '35:5': true
  '35:6': true
  '35:7': true
  '35:8': true
  '35:9': true
  '35:10': true
  '35:11': true
  '35:12': true
  '35:13': true
  '35:14': true
  '35:15': true
  '36': false
  '37': true
  '38': true
  '38:1': true
  '38:2': true
  '38:3': true
  '38:4': true
  '38:5': true
  '38:6': true
  '38:7': true
  '38:8': true
  '39': true
  '40': true
  '41': true
  '42': true
  '43': false
  '43:1': false
  '43:2': false
  '43:3': false
  '43:4': false
  '43:5': false
  '43:6': false
  '43:7': false
  '43:8': false
  '43:9': false
  '44': true
  '44:1': true
  '44:2': true
  '44:3': true
  '44:4': true
  '44:5': true
  '44:6': true
  '44:7': true
  '45': true
  '46': true
  '47': true
  '48': true
  '49': true
  '50': true
  '51': false
  '52': false
  '53': true
  '54': true
  '55': false
  '56': true
  '57': true
  '58': true
  '59': false
  '60': false
  '61': true
  '62': false
  '63': false
  '64': false
  '65': true
  '66': true
  '67': true
  '68': false
  '69': true
  '70': true
  '71': false
  '72': true
  '73': true
  '74': false
  '75': false
  '76': true
  '77': true
  '78': true
  '79': true
  '80': true
  '81': true
  '82': true
  '83': false
  '84': true
  '85': true
  '86': true
  '87': true
  '88': true
  '89': true
  '90': false
  '91': true
  '92': false
  '93': false
  '94': false
  '95': true
  '95:1': true
  '95:2': true
  '95:3': true
  '95:4': true
  '95:5': true
  '95:6': true
  '95:7': true
  '95:8': true
  '95:9': true
  '95:10': true
  '95:11': true
  '95:12': true
  '95:13': true
  '95:14': true
  '95:15': true
  '96': true
  '97': true # to verify
  '97:1': true
  '97:2': true
  '97:3': true
  '97:4': true
  '97:5': true
  '98': true
  '98:1': true
  '98:2': true
  '98:3': true
  '99': true  # to verify
  '100': true  # to verify
  '101': true
  '102': true
  '103': true
  '104': false
  '105': false
  '106': true
  '107': true
  '108': true
  '109': true
  '110': true
  '111': true
  '112': true
  '113': true
  '114': true
  '115': true # to verify
  '116': true
  '117': false
  '118': false
  '119': true # to verify
  '120': true # to verify
  '121': true
  '122': true # to verify
  '123': true
  '125': false
  '125:1': false
  '125:2': false
  '125:3': false
  '125:4': false
  '125:5': false
  '126': true
  '126:1': true
  '126:2': true
  '126:3': true
  '126:4': true
  '126:5': true
  '127': false # to verify
  '128': true
  '129': true
  '130': true
  '131': true
  '132': false
  '133': true
  '134': true
  '135': true
  '136': true
  '137': false
  '138': true
  '139': true
  '139:1': true
  '140': false
  '141': false
  '142': false
  '143': true
  '144': false
  '144:1': false
  '144:2': false
  '144:3': false
  '144:4': false
  '145': true
  '145:1': true
  '145:2': true
  '146': true # verify
  '147': true
  '148': true
  '149': false
  '150': false
  '151': true
  '152': true
  '153': true
  '153': true
  '154': true
  '155': true
  '155:1': true
  '155:2': true
  '156': true
  '157': true
  '158': true
  '159': true
  '159:1': true
  '159:2': true
  '159:3': true
  '159:4': true
  '159:5': true
  '159:6': true
  '159:7': true
  '159:8': true
  '159:9': true
  '159:10': true
  '159:11': true
  '159:12': true
  '159:13': true
  '159:14': true
  '159:15': true
  '160': true
  '160:1': true
  '160:2': true
  '160:3': true
  '160:4': true
  '160:5': true
  '160:6': true
  '160:7': true
  '160:8': true
  '160:9': true
  '160:10': true
  '160:11': true
  '160:12': true
  '160:13': true
  '160:14': true
  '160:15': true
  '161': true
  '161:1': true
  '162': true
  '162:1': true
  '163': true
  '164': true
  '165': true
  '166': false
  '167': true
  '168': true
  '168:1': true
  '168:2': true
  '169': true
  '170': true
  '171': true
  '171:1': true
  '171:2': true
  '171:3': true
  '171:4': true
  '171:5': true
  '171:6': true
  '171:7': true
  '171:8': true
  '171:9': true
  '171:10': true
  '171:11': true
  '171:12': true
  '171:13': true
  '171:14': true
  '171:15': true
  '172': true
  '173': true
  '174': true
  '175': true
  '175:1': true
  '175:2': true
  '175:3': true
  '175:4': true
  '175:5': true
  '176': false
  '177': false
  '178': false
  '179': true
  '179:1': true
  '179:2': true
  '180': true
  '181': true
  '182': true
  '183': true
  '184': true
  '185': true
  '186': true
  '187': true
  '188': true
  '189': true
  '190': true
  '191': true
  '192': true
  '193': false
  '194': false
  '195': false
  '196': false
  '197': false
  '198': false
  '199': false
  '200': false
  '201': false
  '202': false
  '203': false
  '204': false
  '205': false
  '206': false
  '208': false
  '209': false
  '255': false
  '256': true
  '257': true
  '258': true
  '259': true
  '260': true
  '261': true
  '262': true
  '263': true
  '263:1': true
  '264': true
  '265': true
  '266': true
  '267': true
  '268': true
  '269': true
  '270': true
  '271': true
  '272': true
  '273': true
  '274': true
  '275': true
  '276': true
  '277': true
  '278': true
  '279': true
  '280': true
  '281': true
  '282': true
  '283': true
  '284': true
  '285': true
  '286': true
  '287': true
  '288': true
  '289': true
  '290': true
  '291': true
  '292': true
  '293': true
  '294': true
  '295': true
  '296': true
  '297': true
  '298': true
  '299': true
  '300': true
  '301': true
  '302': true
  '303': true
  '304': true
  '305': true
  '306': true
  '307': true
  '308': true
  '309': true
  '310': true
  '311': true
  '312': true
  '313': true
  '314': true
  '315': true
  '316': true
  '317': true
  '318': true
  '319': true
  '320': true
  '321': true
  '322': true
  '323': true
  '324': true
  '325': true
  '326': true
  '327': true
  '328': true
  '329': true
  '330': true
  '331': true
  '332': true
  '333': true
  '334': true
  '335': true
  '336': true
  '337': true
  '338': true
  '339': true
  '340': true
  '341': true
  '342': true
  '343': true
  '344': true
  '345': true
  '346': true
  '347': true
  '348': true
  '349': true
  '349:1': true
  '349:2': true
  '349:3': true
  '350': true
  '350:1': true
  '350:2': true
  '350:3': true
  '351': true
  '351:1': true
  '351:2': true
  '351:3': true
  '351:4': true
  '351:5': true
  '351:6': true
  '351:7': true
  '351:8': true
  '351:9': true
  '351:10': true
  '351:11': true
  '351:12': true
  '351:13': true
  '351:14': true
  '351:15': true
  '352': true
  '353': true
  '354': true
  '355': true
  '356': true
  '357': true
  '358': true
  '359': true
  '360': true
  '361': true
  '362': true
  '363': true
  '364': true
  '365': true
  '366': true
  '367': true
  '368': true
  '369': true
  '370': true
  '371': true
  '372': true
  '373': true
  '373:16': true
  '373:32': true
  '373:64': true
  '373:8193': true
  '373:8194': true
  '373:8195': true
  '373:8196': true
  '373:8197': true
  '373:8198': true
  '373:8200': true
  '373:8201': true
  '373:8202': true
  '373:8204': true
  '373:8205': true
  '373:8206': true
  '373:8225': true
  '373:8226': true
  '373:8228': true
  '373:8229': true
  '373:8233': true
  '373:8235': true
  '373:8236': true
  '373:8257': true
  '373:8258': true
  '373:8259': true
  '373:8260': true
  '373:8262': true
  '373:8264': true
  '373:8265': true
  '373:8266': true
  '373:8267': true
  '373:8269': true
  '373:8270': true
  '373:8289': true #to verify
  '373:8290': true #to verify
  '373:8292': true #to verify
  '373:8297': true #to verify
  '373:16385': true
  '373:16386': true
  '373:16387': true
  '373:16388': true
  '373:16389': true
  '373:16390': true
  '373:16392': true
  '373:16393': true
  '373:16394': true
  '373:16396': true
  '373:16397': true
  '373:16398': true
  '373:16417': true
  '373:16418': true
  '373:16420': true
  '373:16421': true
  '373:16425': true
  '373:16427': true
  '373:16428': true
  '373:16449': true
  '373:16450': true
  '373:16451': true
  '373:16452': true
  '373:16454': true
  '373:16456': true
  '373:16457': true
  '373:16458': true
  '373:16459': true
  '373:16461': true
  '373:16462': true
  '373:16481': true
  '373:16482': true
  '373:16484': true
  '373:16489': true
  '374': true
  '375': true
  '376': true
  '377': true
  '378': true
  '379': true
  '380': true
  '381': true
  '382': true
  '383:50': false
  '383:51': false
  '383:52': false
  '383:53': false
  '383:54': false
  '383:55': false
  '383:56': false
  '383:57': false
  '383:58': false
  '383:59': false
  '383:60': false
  '383:61': false
  '383:62': false
  '383:65': false
  '383:66': false
  '383:67': false
  '383:68': false
  '383:69': false
  '383:90': false
  '383:91': false
  '383:92': false
  '383:93': false
  '383:94': false
  '383:95': false
  '383:96': false
  '383:98': false
  '383:100': false
  '383:101': false
  '383:120': false
  '384': true
  '385': true
  '386': true
  '387': true
  '388': true
  '389': true
  '390': true
  '391': true
  '392': true
  '393': true
  '394': true
  '395': true
  '396': true
  '397': true
  '397:1': true
  '397:2': true
  '397:3': true
  '397:4': true
  '398': true
  '399': true
  '400': true
  '401': true
  '402': true
  '403': true
  '404': true
  '405': true
  '406': true
  '407': true
  '408': true
  '409': true
  '410': true
  '411': true
  '412': true
  '413': true
  '414': true
  '415': true
  '416': true
  '417': true
  '418': true
  '419': true
  '420': true
  '421': true
  '422': false
  '423': true
  '424': true
  '425': true
  '425:1': true
  '425:2': true
  '425:3': true
  '425:4': true
  '425:5': true
  '425:6': true
  '425:7': true
  '425:8': true
  '425:9': true
  '425:10': true
  '425:11': true
  '425:12': true
  '425:13': true
  '425:14': true
  '425:15': true
  '427': true
  '428': true
  '429': true
  '430': true
  '431': true
  '432': false
  '433': false
  '434': false
  '435': false
  '436': false
  '437': false
  '438': false
  '439': false
  '2256': true
  '2257': true
  '2258': true
  '2259': true
  '2260': true
  '2261': true
  '2262': true
  '2263': true
  '2264': true
  '2265': true
  '2266': true
  '2267': true

# List of animals that players will try to collect
creaturesCollection:
- chicken: true
  cow: true
  donkey: true
  horse: true
  iron_golem: true
  mule: true
  mushroom_cow: true
  ocelot: true
  pig: true
  rabbit: true
  sheep: true
  skeleton_horse: true
  snowman: true
  undead_horse: true
  villager: true
  wolf: true
