name: ItemCollector
version: 1.0.0
main: mc.itemcollector.ItemCollector
author: BOG500
description: Collect all the items in Minecraft !

commands:
     itemcollector:
          usage: /itemcollector <list|refresh|count|add|remove|set>
          description: Manage the plugin
     itemcollector list:
          usage: /itemcollector list <items|creatures> <all|missing|collected>
          description: List items or creatures that have been collected so far or that are missing from the collection.
     itemcollector list items:
          usage: /itemcollector list items <all|missing|collected>
          description: List items that have been collected so far or that are missing from the collection.
     itemcollector list creatures:
          usage: /itemcollector list creatures <all|missing|collected>
          description: List creatures that have been collected so far or that are missing from the collection.
     itemcollector refresh:
          usage: /itemcollector refresh <items|creatures>
          description: Force re-count items or creatures
     itemcollector refresh items:
          usage: /itemcollector refresh items
          description: Force re-count items
     itemcollector refresh creatures:
          usage: /itemcollector refresh creatures
          description: Force re-count creatures  
     itemcollector count:
          usage: /itemcollector count
          description: Display the current status of the collection ; how many items and creatures have been collected so for far.
     itemcollector add:
          usage: /itemcollector add <item|creature> <id|name>
          description: Add an item or a creature to the list of items or creatures that must be collected.  For an item, use the minecraft id number (with variant if application.  ie. 2 for grass, 1 for stone, 1:1 for granite), for creatures, use the bukkit name of the creature or its variant (ie. rabbit, pig, cow, horse, undead_horse, donkey).
     itemcollector remove:
          usage: /itemcollector remove <item|creature> <id|name>
          description: Remove an item or a creature to the list of items or creatures that must be collected.  For an item, use the minecraft id number (with variant if application.  ie. 2 for grass, 1 for stone, 1:1 for granite), for creatures, use the bukkit name of the creature or its variant (ie. rabbit, pig, cow, horse, undead_horse, donkey).
     itemcollector set:
          usage: /itemcollector set <region|option|message>
          description: Change configuration
     itemcollector set region:
          usage: /itemcollector set region minX maxX minZ maxZ
          description: Set the boundaries of the region where the collection must be.  ItemCollector will only look for items and creatures in this area.